---
title: "Analysis of ATAC-seq Ctl samples"
output: html_notebook
---

```{r, setup}
library(tidyverse)
library(patchwork)
library(edgeR)
library(limma)
library(omisc)
library(ComplexHeatmap)
theme_set(cowplot::theme_cowplot())
```

# Load data

```{r}
x <- read_rds("/Users/sunxin/Documents/Projects/atacseq/new_update_20220912/dge.rds")
x
```

# Filter samples

```{r}
x <- x[, x$samples$condition == "Ctl"]
x
```

# Filter and normalize

```{r}
keep <- rowSums(cpm(x) > 1) >= 2
table(keep)
x <- x[keep, , keep.lib.sizes = TRUE]

x <- calcNormFactors(x, method = "TMM")
```

# Statistical analysis

```{r}
design <- model.matrix(~ 0 + background, x$samples)
rownames(design) <- colnames(x)
colnames(design) <- sub("background", "", colnames(design))
design
```

```{r voom}
v <- voom(x, design, plot = FALSE, save.plot = TRUE)
plot_voom(v)
```

```{r}
fit <- lmFit(v, design)
```

```{r}
con <- makeContrasts(
  KOvsWT=KO - WT,
  levels = design
)
con
```

```{r}
fit2 <- contrasts.fit(fit, con)
fit2 <- eBayes(fit2)
```

```{r pvalue_hist}
plot_hist(fit2)
```

```{r}
topTable(fit2)
```

```{r}
top <- topTable(fit2, coef = "KOvsWT", number = Inf)
head(top)
```

## Ctl

```{r}
ids <- rownames(topTable(fit2, coef="KOvsWT", p.value=0.05, sort.by="logFC", n=200))
```

```{r fig.width=7, fig.height=28}
omisc::plot_heatmap(x[ids, ], scale=TRUE)
```

```{r}
top_100 <- head(top, 100)
```

## Fig.5C

```{r}
omisc::plot_heatmap(x[rownames(top_100), ], show_row_names=FALSE)
```


```{r}
top_dar <- topTable(fit2, coef="KOvsWT", n=Inf)
head(top_dar)
```

## Fig.S5A

```{r}
top_dar <- top_dar |> 
  mutate(DAR=factor(ifelse(adj.P.Val < 0.01, "KOvsWT", "Not DAR"))) |> 
  mutate(DAR=relevel(DAR, "Not DAR")) |> 
  drop_na()

ggplot(top_dar, aes(DAR, fill=Region)) +
  geom_bar(position="fill")
```


```{r}
top_p <- top[top$adj.P.Val <= 0.01,]
foo <- top_p$SYMBOL
head(foo)
```

```{r}
genes <- c( "Arnt2" ,  "Bmi1" ,   "Zfp36l1", "Klf5" ,   "Camk4",   "Cdkn2d" , "Cebpd"  , "Cops2" ,  "Egr2" ,   "Eomes" ,  "Fosl2" ,  "Gas7"  ,  "Hdac5", "Hmga1" ,  "Ifnar2" , "Irf2" ,   "Irf4"  ,  "Klf2" ,   "Lef1"  ,  "Mbd2" ,   "Mef2c" ,  "Foxk1"  , "Cited2" , "Nab2" ,  "Nfatc1" , "Nfatc2" , "Nfe2l1" , "Nfkb1" ,  "Pou2f2"  ,"Tcf7l2" , "Tle4"   , "Ncoa4"  , "Snai3" ,  "Rab11a"  ,"Prdm5"  , "Uhrf2" ,  "Ell2" ,   "Trerf1" , "Rab8b"  ,"Dmrta1",  "E2f2" ,   "Irf2bp1" )
id <-which(top_p$SYMBOL %in% genes)
tfid<- top_p[id,]
```

```{r, fig.height=12, fig.width=5}
foo <-x[rownames(tfid), ]
omisc::plot_heatmap(x[rownames(tfid), ], scale=TRUE)
```

## Fig.S5B

```{r, fig.height=15, fig.width=8}
name <- paste0(foo$genes$SYMBOL,"_", rownames(foo))
foo$genes$SYMBOL <- name
omisc::plot_heatmap(foo, scale=TRUE)
```


# Session information

```{r}
sessionInfo()
```
